st <- data.frame(state.x77, state.region)

str(st)

class(st)
head(st)
dim(st)
table(st$state.region)

summary(st[, 1])
summary(st[, 2])
summary(st[, 'Illiteracy'])
summary(st$Life.Exp)
summary(st[, 5])
summary(st[, 6])
summary(st[, 'Frost'])
summary(st$Area)

sd(st[, 1])
sd(st[, 2])
sd(st[, 'Illiteracy'])
sd(st$Life.Exp)
sd(st[, 5])
sd(st[, 6])
sd(st[, 'Frost'])
sd(st$Area)

par(mfrow = c(2, 4))
boxplot(Population~state.region, data = st, main = 'Population')
boxplot(Income~state.region, data = st, main = 'Income')
boxplot(Illiteracy~state.region, data = st, main = 'Illiteracy')
boxplot(Life.Exp ~ state.region, data = st, main = 'Life.Exp')
boxplot(Murder~state.region, data = st, main = 'Murder')
boxplot(HS.Grad~state.region, data = st, main = 'HS.Grad')
boxplot(Frost~state.region, data = st, main = 'Frost')
boxplot(Area ~ state.region, data = st, main = 'Area')

point <- as.numeric(st$state.region)
color <- c('red', 'green', 'blue', 'black')
pairs(st[, -9], pch = c(point), col = color[st[, 9]])

cor(st$Murder, st$Population)
cor(st$Murder, st$Income)
cor(st$Murder, st$Illiteracy)
cor(st$Murder, st$Life.Exp)
cor(st$Murder, st$HS.Grad)
cor(st$Murder, st$Frost)
cor(st$Murder, st$Area)